on:
  push:
    branches:
      - 'add-BLTNA-promo-github-actions-workflow'
      - 'update-BLTNA-promo-github-actions-workflow'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 21 * * *'

name: Download BLTNA data from PoolTool

jobs:
  get-pooltool-data:
    name: Get PoolTool data
    runs-on: ubuntu-latest
    steps:
      - name: Set Pool ID for BLTNA
        id: ITNv1_setPOOL
        run: echo "::set-output name=ID::0359c9a1b26be45a91a4ddb1d02fb9c0f6d779ed5e515924ee1597f272336064"
      - name: Get epoch stakers for BLTNA
        id: ITNv1_getStakers
        run: |
          JSON=$(curl --proto '=https' --tlsv1.2 -sSf \
            "https://pooltool.s3-us-west-2.amazonaws.com/8e4d2a3/pools/${{ steps.ITNv1_setPOOL.outputs.ID }}/currentstakers.json")
          EPOCH_NR=$(echo ${JSON} | jq -r .epoch )
          mkdir JSON
          echo ${JSON} > JSON/BLTNA_EPOCH_${EPOCH_NR}_STAKERS_ALL.json
          echo ${JSON} | jq -r 'del(.updatedAt,.epoch) | del(.d[] | select(.stake == 0))' > JSON/BLTNA_EPOCH_${EPOCH_NR}_STAKERS_CURRENT.json
          echo "::set-output name=EPOCH_NR::${EPOCH_NR}"
      - name: Upload BLTNA ITNv1 stakers data for all epochs
        uses: actions/upload-artifact@v1
        with:
          name: BLTNA_EPOCH_${{ steps.ITNv1_getStakers.outputs.EPOCH_NR }}_STAKERS
          path: JSON